services:
  website:
    image: smokingplayaru:latest
    container_name: smokingplayaru
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped